name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "/home/runner/work/sofa-dashboard/sofa-dashboard/sofa-jobs/sofa-jobs-agent-bootstrap/target/sofa-jobs-agent-bootstrap.jar,/home/runner/work/sofa-dashboard/sofa-dashboard/sofa-jobs/sofa-jobs-bootstrap/target/sofa-jobs-bootstrap.jar"
        target: "test"
    - name: restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          pwd
          ~/jobs/bin/restart.sh sofa-jobs-bootstrap
          ~/jobs/bin/restart.sh sofa-jobs-agent-bootstrap
